apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bystander
  name: bystander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bystander
  template:
    metadata:
      labels:
        app: bystander
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bystander
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: bystander
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bystander
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: "bystander.sattest.moneylion.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: bystander
              servicePort: 80
