apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: saturation-server
  name: saturation-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saturation-server
  template:
    metadata:
      labels:
        app: saturation-server
    spec:
      containers:
      - image: dixont/ws_server
        name: ws-server
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: saturation-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: saturation-server
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: saturation-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: "ws.sattest.moneylion.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: saturation-server
              servicePort: 8080